package:
  name: openalea.mtg
  version: 2.0.0

source:
  git_url: https://github.com/openalea/mtg


build:
  preserve_egg_dir: True

requirements:
  build:
    - python
    - setuptools
    - openalea.deploy
  run:
    - python
    - setuptools
    - openalea.deploy
    - openalea.core
    - numpy
    - matplotlib
    - vplants.plantgl

test:
  imports:
    - openalea.mtg

about:
  home: http://openalea.gforge.inria.fr/
  license: Cecill-C License