package:
  name: eigen
  version: 3.3.4

source:
  fn: eigen3-3.3.4.tar.gz
  url: http://bitbucket.org/eigen/eigen/get/3.3.4.tar.bz2

build:
  number: 1

requirements:
  build:

about:
  home: http://eigen.tuxfamily.org/
  license: MPL2
  summary: 'C++ template library for linear algebra'
