# WARNING : This recipe is built using the command line:
# conda build -c defaults -c openalea vplants.sequence_analysis

package:
  name: vplants.sequence_analysis
  version: 1.3.0

source:
  git_url: https://github.com/VirtualPlants/StructureAnalysis
  patches:
   # List any patch files here
   - setup.patch
   - SConstruct.patch

about:
  home: http://openalea.gforge.inria.fr
  license: GPL/LGPL
  summary: Tool for stat and sequence analysis

build:
  preserve_egg_dir: True
  number: 1


requirements:
  # it doesn't really require python, but maybe that will fix
  # the missing bin directory
  build:
   - python
   - setuptools
   - openalea.deploy
   - scons
   - openalea.sconsx
   - readline
   - qt 4.8.6
   - vplants.tool
   - vplants.stat_tool
   - boost 1.57.0
  run:
   - python
   - readline
   - qt 4.8.6
   - vplants.tool
   - vplants.stat_tool
   - boost 1.57.0

