{% set version = "5.0.4" %}
{% set sha256 = "151cb845728bde75eb9d1561b35140114a05a7c52a52bd35b4b2b3d944e0c31e" %}
{% set CONDA_NCURSES = "5.9" %}

package:
  name: gnuplot
  version: {{ version }}

build:
  number: 0
  string: "ncurses{{CONDA_NCURSES}}_{{PKG_BUILDNUM}}"

source:
  url: https://sourceforge.net/projects/gnuplot/files/gnuplot/{{ version }}/gnuplot-{{ version }}.tar.gz
  fn: gnuplot-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - gcc [not osx]
    - llvm [osx]
    - pkg-config [osx]
    - libgd
    - ncurses {{CONDA_NCURSES}}*
    - qt 4.8.6
    - readline
  run:
    - libgcc [not osx]
    - libgd
    - ncurses {{CONDA_NCURSES}}*
    - qt 4.8.6
    - readline

about:
  home: https://github.com/gnuplot/gnuplot
  license: Gnuplot License + others
  summary: Gnuplot, plotting from command line

test:
  files:
    - test-data.txt
  commands:
    - gnuplot -e "set terminal dumb; set style histogram; p 'test-data.txt'"
    - gnuplot -e "set terminal png"
