package:
  name: vplants.lpy
  version: 2.5.1

source:
  git_url: https://github.com/openalea/lpy
  patches:
   # List any patch files here
   - setup.patch

about:
  home: http://openalea.gforge.inria.fr
  license: GPL/LGPL
  summary: A Python version of Lindenmayer Systems.

build:
  preserve_egg_dir: True
  number: 2

requirements:
  # it doesn't really require python, but maybe that will fix
  # the missing bin directory
  build:
   - python
   - m4
   - setuptools
   - openalea.deploy
   - scons
   - openalea.sconsx
   - readline
   - qt ==4.8.6 [osx]
   - qt ==4.8.7 [linux]
   - boost [osx]
   - boost [linux]
   - bison
   - flex 2.5.39
   - cgal  [osx]
   - cgal  [linux]
   - gmp
   - ann
   - eigen 3.2.8 [osx]
   - eigen [linux]
   - qhull
   - vplants.plantgl
  run:
   - python
   - readline
   - qt ==4.8.6 [osx]
   - qt ==4.8.7 [linux]
   - gmp
   - mpfr
   - cgal  [osx]
   - cgal  [linux]
   - qhull
   - ann
   - boost [osx]
   - boost [linux]
   - vplants.plantgl
   - openalea.core
   - openalea.vpltk
   - openalea.oalab
   - pyopengl
   - pyqglviewer

#test:
  # Python imports
  #imports:
  #  - openalea.lpy

