package:
  name: pyqglviewer
  version: 1.0.0

source:
  git_url: https://github.com/fredboudon/PyQGLViewer
  #fn: PyQGLViewer-0.14.1.tgz
  #url: https://gforge.inria.fr/frs/download.php/file/35463/PyQGLViewer-0.14.1.tgz
  patches:
   # List any patch files here
   - configure.py.patch
   #- examples.pri.patch
   #- libQGLViewer.pro.patch


build:
  number: 0
  features:
    - vc9               [win and py27]
    - vc10              [win and py34]
    - vc14              [win and py35]

requirements:
  build:
    - python
    - sip
    - qt <5
    - pyqt
    - libqglviewer

  run:
    # python dependency is here due to libboost-python library that depends on
    # python version
    - python
    - qt <5
    - pyqt
    - libqglviewer
    - pyopengl

about:
  home: https://github.com/fredboudon/PyQGLViewer
  license: GPL
  summary: PyQGLViewer is a set of Python bindings for the libQGLViewer C++ library which extends the Qt framework with widgets and tools that eases the creation of OpenGL 3D viewers.


