package:
  name: pyqglviewer
  version: 0.14

source:
  fn: PyQGLViewer-0.14.1.tgz
  url: https://gforge.inria.fr/frs/download.php/file/35463/PyQGLViewer-0.14.1.tgz
  patches:
   # List any patch files here
   - configure.py.patch
   #- examples.pri.patch
   #- libQGLViewer.pro.patch


build:
  number: 0
  features:
    - vc9               [win and py27]
    - vc10              [win and py34]
    - vc14              [win and py35]

requirements:
  build:
    - python
    - sip
    - qt 4.8.6 [osx]
    - qt 4.8.7 [linux]
    - pyqt
    - libqglviewer

  run:
    # python dependency is here due to libboost-python library that depends on
    # python version
    - python
    - qt 4.8.6 [osx]
    - qt 4.8.7 [linux]
    - pyqt
    - libqglviewer
    - pyopengl

about:
  home: http://www.libqglviewer.com
  license: GPL

