package:
  name: boost
  version: 1.57.0

source:
  fn:  boost_1_57_0.tar.bz2
  url: http://sourceforge.net/projects/boost/files/boost/1.57.0/boost_1_57_0.tar.bz2
  #md5: 6095876341956f65f9d35939ccea1a9f

build:
  features:
    - vc9               [win and py27]
    - vc14              [win and py36]
  track_features:
    - vc9               [win and py27]
    - vc14              [win and py36]

requirements:
  build:
    - python
    - vs2008_runtime    [win and py27]
    - vs2015_runtime    [win and py36]
    - icu 54.*          [unix]
    - bzip2             [unix]
    - zlib

  run:
    # python dependency is here due to libboost-python library that depends on
    # python version
    - python
    - icu 54.*          [unix]
    - zlib

about:
  home: http://www.boost.org/
  license: Boost-1.0

