{% set version_win = "1.64.0" %}
{% set filename_win = "boost_%s.tar.bz2" % version_win.replace(".", "_") %}
{% set sha_win = "7bcc5caace97baa948931d712ea5f37038dbb1c5d89b43ad4def4ed7cb683332" %}

{% set version_unix = "1.65.1" %}
{% set filename_unix = "boost_%s.tar.bz2" % version_unix.replace(".", "_") %}
{% set sha_unix = "9807a5d16566c57fd74fb522764e0b134a8bbe6b6e8967b83afefd30dcd3be81" %}



package:
  name: boost
  version: {{ version_unix }}   [unix]
  version: {{ version_win }}    [win]

source:
  fn:  {{ filename_win }}       [win]
  url: https://dl.bintray.com/boostorg/release/{{ version_win }}/source/{{ filename_win }}  [win]
  sha256: {{ sha_win }}  [win]

  fn:  {{ filename_unix }}       [unix]
  url: https://dl.bintray.com/boostorg/release/{{ version_unix }}/source/{{ filename_unix }}  [unix]
  sha256: {{ sha_unix }}  [unix]

build:
  features:
    - vc9               [win and py27]
    - vc14              [win and py36]
  track_features:
    - vc9               [win and py27]
    - vc14              [win and py36]

requirements:
  build:
    - python
    - numpy
    - vs2008_runtime    [win and py27]
    - vs2015_runtime    [win and py36]
    - icu 54.*          [unix]
    - bzip2             [unix]
    - zlib

  run:
    # python dependency is here due to libboost-python library that depends on
    # python version
    - python
    - numpy
    - icu 54.*          [unix]
    - zlib

about:
  home: http://www.boost.org/
  license: Boost-1.0

