{% set version = "1.64.0" %}
{% set filename = "boost_%s.tar.bz2" % version.replace(".", "_") %}

package:
  name: boost
  version: {{ version }}

source:
  fn:  {{ filename }}
  url: https://dl.bintray.com/boostorg/release/{{ version }}/source/{{ filename }}
  sha256: 7bcc5caace97baa948931d712ea5f37038dbb1c5d89b43ad4def4ed7cb683332

build:
  features:
    - vc9               [win and py27]
    - vc14              [win and py36]
  track_features:
    - vc9               [win and py27]
    - vc14              [win and py36]

requirements:
  build:
    - python
    - numpy
    - vs2008_runtime    [win and py27]
    - vs2015_runtime    [win and py36]
    - icu 54.*          [unix]
    - bzip2             [unix]
    - zlib

  run:
    # python dependency is here due to libboost-python library that depends on
    # python version
    - python
    - numpy
    - icu 54.*          [unix]
    - zlib

about:
  home: http://www.boost.org/
  license: Boost-1.0

