package:
  name: cgal
  version: 4.11.0

source:
   fn: CGAL-4.11.tar.gz
   url: https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-4.11/CGAL-4.11.zip
   md5: 320d70f7fd2a98537d20e21eeaea5a25

about:
  home: http://www.cgal.org/
  license: GPL/LGPL
  summary: robust C++ implementation of geometric algorithms

# needs boost - this is now in defaults.  the ioos boost is broken (and has been
# deprecated but still appears in the channel - 2015-08-02)

requirements:
  # it doesn't really require python, but maybe that will fix
  # the missing bin directory
  build:
   - boost 
   - python
   - cmake
   - mpfr
   - gmp
   - qt <5
   - patchelf [linux]
  run:
   - boost
   - gmp
   - mpfr
   - qt <5
