package:
  name: cgal
  version: 4.6.3

source:
   fn: CGAL-4.6.3.tar.gz
   url: http://gforge.inria.fr/frs/download.php/file/35138/CGAL-4.6.3.tar.gz

about:
  home: http://www.cgal.org/
  license: GPL/LGPL
  summary: robust C++ implementation of geometric algorithms

# needs boost - this is now in defaults.  the ioos boost is broken (and has been
# deprecated but still appears in the channel - 2015-08-02)

requirements:
  # it doesn't really require python, but maybe that will fix
  # the missing bin directory
  build:
   - boost ==1.57
   - python
   - cmake
   - mpfr
   - gmp
   - qt <5
  run:
   - boost ==1.57
   - gmp
   - mpfr
   - qt <5
