package:
  name: cgal
  version: 4.11.0

source:
   fn: CGAL-4.11.zip
   url: https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-4.11/CGAL-4.11.zip
   md5: 320d70f7fd2a98537d20e21eeaea5a25

about:
  home: http://www.cgal.org/
  license: GPL/LGPL
  summary: robust C++ implementation of geometric algorithms

build:
    features:
      - vc9               [win and py27]
      - vc14              [win and py36]

requirements:
  build:
   - cmake
   - eigen
   - mpfr
   - gmp [unix]
   - mpir
   - boost
   - zlib
  run:
   - boost
   - gmp [unix]
   - mpfr
