package:
    name: ann
    version: "1.1.2"

source:
    fn: ann_1.1.2.tar.gz
    url: http://www.cs.umd.edu/~mount/ANN/Files/1.1.2/ann_1.1.2.tar.gz
    md5: 7ffaacc7ea79ca39d4958a6378071365

    patches:
        - patches/cmake.patch


build:
  detect_binary_files_with_prefix: true

requirements:
  build:
    - cmake
    - vs2013_runtime [win]
    - patch

# Note: tests are run when building the package, they are not accessible
# in the installed package.

about:
    home: http://www.cs.umd.edu/~mount/ANN/
    license: GNU Lesser General Public License (LGPL)
summary: 'ANN: A Library for Approximate Nearest Neighbor Searching'