package:
  name: scons
  version: 3.0.1

source:
  fn: scons-3.0.1.tar.gz
  url: http://prdownloads.sourceforge.net/scons/scons-3.0.1.tar.gz

requirements:
  build:
    - python
    - setuptools
  run:
    - python

build:
  number: 0
  script: python setup.py install --standard-lib

test:
  imports:
    - SCons
    - SCons.Node
    - SCons.Options
    - SCons.Platform
    - SCons.Scanner
    - SCons.Script
    - SCons.Tool
    - SCons.Tool.MSCommon
    - SCons.Tool.docbook
    - SCons.Tool.packaging
    - SCons.Variables
    - SCons.compat

about:
  home: http://www.scons.org
  license: MIT License
  summary: 'Open Source next-generation build tool.'
  description: |
    SCons is an Open Source software construction tool that is, a
    next-generation build tool. Think of SCons as an improved, cross-platform
    substitute for the classic Make utility with integrated functionality
    similar to autoconf/automake and compiler caches such as ccache. In short,
    SCons is an easier, more reliable and faster way to build software.
  doc_url: http://scons.org/documentation.html
  dev_url: https://github.com/SConsProject/scons
